// src/components/spec-avatar-list/spec-avatar-list.component.ts
import { Component, OnInit } from "../../utils";
@Component({
    tag: 'spec-avatar-list',
    styleUrl: './spec-avatar-list.component.scss',
    templateUrl: './spec-avatar-list.component.html'
})
export class SpecAvatarListComponent extends HTMLElement implements OnInit {
    constructor(
    ) {
        super();
        this.onInit();     
    }    

    onInit(): void {
    }
}
<div class="spec-avatar__list">
    <div class="spec__avatar">
        <img src="/src/img/samoilof.svg">
        <div class="spec-counter__wrapper">
            <span class="spec-counter">7</span>
        </div>
    </div>
</div>

// src/components/controls/spec-avatar-list/SpecAvatarList.tsx
import React from 'react'

import './SpecAvatarList.scss'
import samoilof from '../../../assets/img/samoilof.svg'

export const SpecAvatarList = () => {
    return (
        <div className="left__control">
            <div className="spec-avatar__list">
                <div className="spec__avatar">
                    <img src={samoilof} alt="Аватарка специалиста"/>
                    <div className="spec-counter__wrapper">
                        <span className="spec-counter">7</span>
                    </div>
                </div>
            </div>
            <div className="add-spec__control">
                <button className="add-spec__button">+</button>
                <span>Добавить специалиста</span>
            </div>
        </div>
    );
}
